In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.tail()

,movie_id,title,cast,crew
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
movies = movies.merge(credits, on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
movies=movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace = True)

In [12]:
movies.duplicated().sum()

np.int64(0)

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [15]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies['keywords'] = movies['keywords'].apply(convert)

NameError: name 'ast' is not defined

In [ ]:
movies.head()

In [ ]:
import ast

def convert3(obj):
    if isinstance(obj, str):  # only parse if it's a string
        obj = ast.literal_eval(obj)

    L = []
    for i in obj[:3]:  # simpler than using a counter
        L.append(i['name'] if isinstance(i, dict) else i)
    return L

In [ ]:
movies['cast'] = movies['cast'].apply(convert3)

In [ ]:
movies.head()

In [17]:
import ast
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [18]:
movies['crew']

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...
4804    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4806, dtype: object

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [21]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
import ast
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [24]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [26]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [27]:
movies['genres'] = movies['genres'].apply(convert)

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [29]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton]

In [31]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [33]:
movies.tags

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4806, dtype: object

In [34]:
new_df = movies[['movie_id', 'title', 'tags']]

In [35]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

C:\Users\khada\AppData\Local\Temp\ipykernel_19852\3530946481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [37]:
import nltk

In [38]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [39]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [40]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\khada\AppData\Local\Temp\ipykernel_19852\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [41]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict [ { " i d " : 1 4 6 3 , " n a m e " : " c u l t u r e c l a s h " } , { " i d " : 2 9 6 4 , " n a m e " : " f u t u r e " } , { " i d " : 3 3 8 6 , " n a m e " : " s p a c e w a r " } , { " i d " : 3 3 8 8 , " n a m e " : " s p a c e c o l o n y " } , { " i d " : 3 6 7 9 , " n a m e " : " s o c i e t y " } , { " i d " : 3 8 0 1 , " n a m e " : " s p a c e t r a v e l " } , { " i d " : 9 6 8 5 , " n a m e " : " f u t u r i s t i c " } , { " i d " : 9 8 4 0 , " n a m e " : " r o m a n c e " } , { " i d " : 9 8 8 2 , " n a m e " : " s p a c e " } , { " i d " : 9 9 5 1 , " n a m e " : " a l i e n " } , { " i d " : 1 0 1 4 8 , " n a m e " : " t r i b e " } , { " i d " : 1 0 1 5 8 , " n a m e " : " a l i e n p l a n e t " } , { " i d " : 1 0 9 8 7 , " n a m e " : " c g i " } , { " i d " : 1 1 3 9 9 , " n a m e " : " m a r i n e " } , { " i d " : 1 3 0 6 5 , " n a m e " : " s o l d i e r " } , { " i d " : 1 4 6 4 3 , " n a m e " : " b a t t l e " } , { " i d " : 1 4 7 2 0 , " n a m e " : " l o v e a f f a i r " } , { " i d " : 1 6 5 4 3 1 , " n a m e " : " a n t i w a r " } , { " i d " : 1 9 3 5 5 4 , " n a m e " : " p o w e r r e l a t i o n s " } , { " i d " : 2 0 6 6 9 0 , " n a m e " : " m i n d a n d s o u l " } , { " i d " : 2 0 9 7 1 4 , " n a m e " : " 3 d " } ] [ { " c a s t _ i d " : 2 4 2 , " c h a r a c t e r " : " j a k e s u l l y " , " c r e d i t _ i d " : " 5 6 0 2 a 8 a 7 c 3 a 3 6 8 5 5 3 2 0 0 1 c 9 a " , " g e n d e r " : 2 , " i d " : 6 5 7 3 1 , " n a m e " : " s a m w o r t h i n g t o n " , " o r d e r " : 0 } , { " c a s t _ i d " : 3 , " c h a r a c t e r " : " n e y t i r i " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c b " , " g e n d e r " : 1 , " i d " : 8 6 9 1 , " n a m e " : " z o e s a l d a n a " , " o r d e r " : 1 } , { " c a s t _ i d " : 2 5 , " c h a r a c t e r " : " d r . g r a c e a u g u s t i n e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 9 " , " g e n d e r " : 1 , " i d " : 1 0 2 0 5 , " n a m e " : " s i g o u r n e y w e a v e r " , " o r d e r " : 2 } , { " c a s t _ i d " : 4 , " c h a r a c t e r " : " c o l . q u a r i t c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c f " , " g e n d e r " : 2 , " i d " : 3 2 7 4 7 , " n a m e " : " s t e p h e n l a n g " , " o r d e r " : 3 } , { " c a s t _ i d " : 5 , " c h a r a c t e r " : " t r u d y c h a c o n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 3 " , " g e n d e r " : 1 , " i d " : 1 7 6 4 7 , " n a m e " : " m i c h e l l e r o d r i g u e z " , " o r d e r " : 4 } , { " c a s t _ i d " : 8 , " c h a r a c t e r " : " s e l f r i d g e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 1 " , " g e n d e r " : 2 , " i d " : 1 7 7 1 , " n a m e " : " g i o v a n n i r i b i s i " , " o r d e r " : 5 } , { " c a s t _ i d " : 7 , " c h a r a c t e r " : " n o r m s p e l l m a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d d " , " g e n d e r " : 2 , " i d " : 5 9 2 3 1 , " n a m e " : " j o e l d a v i d m o o r e " , " o r d e r " : 6 } , { " c a s t _ i d " : 9 , " c h a r a c t e r " : " m o a t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 5 " , " g e n d e r " : 1 , " i d " : 3 0 4 8 5 , " n a m e " : " c c h p o u n d e r " , " o r d e r " : 7 } , { " c a s t _ i d " : 1 1 , " c h a r a c t e r " : " e y t u k a n " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e d " , " g e n d e r " : 2 , " i d " : 1 5 8 5 3 , " n a m e " : " w e s s t u d i " , " o r d e r " : 8 } , { " c a s t _ i d " : 1 0 , " c h a r a c t e r " : " t s u \' t e y " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 e 9 " , " g e n d e r " : 2 , " i d " : 1 0 9 6 4 , " n a m e " : " l a z a l o n s o " , " o r d e r " : 9 } , { " c a s t _ i d " : 1 2 , " c h a r a c t e r " : " d r . m a x p a t e l " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 1 " , " g e n d e r " : 2 , " i d " : 9 5 6 9 7 , " n a m e " : " d i l e e p r a o " , " o r d e r " : 1 0 } , { " c a s t _ i d " : 1 3 , " c h a r a c t e r " : " l y l e w a i n f l e e t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f 5 " , " g e n d e r " : 2 , " i d " : 9 8 2 1 5 , " n a m e " : " m a t t g e r a l d " , " o r d e r " : 1 1 } , { " c a s t _ i d " : 3 2 , " c h a r a c t e r " : " p r i v a t e f i k e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 b " , " g e n d e r " : 2 , " i d " : 1 5 4 1 5 3 , " n a m e " : " s e a n a n t h o n y m o r a n " , " o r d e r " : 1 2 } , { " c a s t _ i d " : 3 3 , " c h a r a c t e r " : " c r y o v a u l t m e d t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 f " , " g e n d e r " : 2 , " i d " : 3 9 7 3 1 2 , " n a m e " : " j a s o n w h y t e " , " o r d e r " : 1 3 } , { " c a s t _ i d " : 3 4 , " c h a r a c t e r " : " v e n t u r e s t a r c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 3 " , " g e n d e r " : 2 , " i d " : 4 2 3 1 7 , " n a m e " : " s c o t t l a w r e n c e " , " o r d e r " : 1 4 } , { " c a s t _ i d " : 3 5 , " c h a r a c t e r " : " l o c k u p t r o o p e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 7 " , " g e n d e r " : 2 , " i d " : 9 8 6 7 3 4 , " n a m e " : " k e l l y k i l g o u r " , " o r d e r " : 1 5 } , { " c a s t _ i d " : 3 6 , " c h a r a c t e r " : " s h u t t l e p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 2 7 , " n a m e " : " j a m e s p a t r i c k p i t t " , " o r d e r " : 1 6 } , { " c a s t _ i d " : 3 7 , " c h a r a c t e r " : " s h u t t l e c o - p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 6 f " , " g e n d e r " : 0 , " i d " : 1 1 8 0 9 3 6 , " n a m e " : " s e a n p a t r i c k m u r p h y " , " o r d e r " : 1 7 } , { " c a s t _ i d " : 3 8 , " c h a r a c t e r " : " s h u t t l e c r e w c h i e f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 3 " , " g e n d e r " : 2 , " i d " : 1 0 1 9 5 7 8 , " n a m e " : " p e t e r d i l l o n " , " o r d e r " : 1 8 } , { " c a s t _ i d " : 3 9 , " c h a r a c t e r " : " t r a c t o r o p e r a t o r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 7 " , " g e n d e r " : 0 , " i d " : 9 1 4 4 3 , " n a m e " : " k e v i n d o r m a n " , " o r d e r " : 1 9 } , { " c a s t _ i d " : 4 0 , " c h a r a c t e r " : " d r a g o n g u n s h i p p i l o t " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 b " , " g e n d e r " : 2 , " i d " : 1 7 3 3 9 1 , " n a m e " : " k e l s o n h e n d e r s o n " , " o r d e r " : 2 0 } , { " c a s t _ i d " : 4 1 , " c h a r a c t e r " : " d r a g o n g u n s h i p g u n n e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 7 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 3 6 , " n a m e " : " d a v i d v a n h o r n " , " o r d e r " : 2 1 } , { " c a s t _ i d " : 4 2 , " c h a r a c t e r " : " d r a g o n g u n s h i p n a v i g a t o r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 3 " , " g e n d e r " : 0 , " i d " : 2 1 5 9 1 3 , " n a m e " : " j a c o b t o m u r i " , " o r d e r " : 2 2 } , { " c a s t _ i d " : 4 3 , " c h a r a c t e r " : " s u i t # 1 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 7 " , " g e n d e r " : 0 , " i d " : 1 4 3 2 0 6 , " n a m e " : " m i c h a e l b l a i n - r o z g a y " , " o r d e r " : 2 3 } , { " c a s t _ i d " : 4 4 , " c h a r a c t e r " : " s u i t # 2 " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 b " , " g e n d e r " : 2 , " i d " : 1 6 9 6 7 6 , " n a m e " : " j o n c u r r y " , " o r d e r " : 2 4 } , { " c a s t _ i d " : 4 6 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 8 f " , " g e n d e r " : 0 , " i d " : 1 0 4 8 6 1 0 , " n a m e " : " l u k e h a w k e r " , " o r d e r " : 2 5 } , { " c a s t _ i d " : 4 7 , " c h a r a c t e r " : " a m b i e n t r o o m t e c h / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 3 " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " n a m e " : " w o o d y s c h u l t z " , " o r d e r " : 2 6 } , { " c a s t _ i d " : 4 8 , " c h a r a c t e r " : " h o r s e c l a n l e a d e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 7 " , " g e n d e r " : 2 , " i d " : 6 8 2 7 8 , " n a m e " : " p e t e r m e n s a h " , " o r d e r " : 2 7 } , { " c a s t _ i d " : 4 9 , " c h a r a c t e r " : " l i n k r o o m t e c h " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 7 , " n a m e " : " s o n i a y e e " , " o r d e r " : 2 8 } , { " c a s t _ i d " : 5 0 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r / t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 9 f " , " g e n d e r " : 1 , " i d " : 1 2 0 7 2 4 8 , " n a m e " : " j a h n e l c u r f m a n " , " o r d e r " : 2 9 } , { " c a s t _ i d " : 5 1 , " c h a r a c t e r " : " b a s k e t b a l l a v a t a r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 3 " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " n a m e " : " i l r a m c h o i " , " o r d e r " : 3 0 } , { " c a s t _ i d " : 5 2 , " c h a r a c t e r " : " n a \' v i c h i l d " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 4 9 , " n a m e " : " k y l a w a r r e n " , " o r d e r " : 3 1 } , { " c a s t _ i d " : 5 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 0 , " n a m e " : " l i s a r o u m a i n " , " o r d e r " : 3 2 } , { " c a s t _ i d " : 5 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a a f " , " g e n d e r " : 1 , " i d " : 8 3 1 0 5 , " n a m e " : " d e b r a w i l s o n " , " o r d e r " : 3 3 } , { " c a s t _ i d " : 5 7 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 3 , " n a m e " : " c h r i s m a l a " , " o r d e r " : 3 4 } , { " c a s t _ i d " : 5 5 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 1 , " n a m e " : " t a y l o r k i b b y " , " o r d e r " : 3 5 } , { " c a s t _ i d " : 5 6 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 2 , " n a m e " : " j o d i e l a n d a u " , " o r d e r " : 3 6 } , { " c a s t _ i d " : 5 8 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a b f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 4 , " n a m e " : " j u l i e l a m m " , " o r d e r " : 3 7 } , { " c a s t _ i d " : 5 9 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 7 , " n a m e " : " c u l l e n b . m a d d e n " , " o r d e r " : 3 8 } , { " c a s t _ i d " : 6 0 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 5 9 , " n a m e " : " j o s e p h b r a d y m a d d e n " , " o r d e r " : 3 9 } , { " c a s t _ i d " : 6 1 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 2 , " n a m e " : " f r a n k i e t o r r e s " , " o r d e r " : 4 0 } , { " c a s t _ i d " : 6 2 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a c f " , " g e n d e r " : 1 , " i d " : 1 1 5 8 6 0 0 , " n a m e " : " a u s t i n w i l s o n " , " o r d e r " : 4 1 } , { " c a s t _ i d " : 6 3 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 3 " , " g e n d e r " : 1 , " i d " : 9 8 3 7 0 5 , " n a m e " : " s a r a w i l s o n " , " o r d e r " : 4 2 } , { " c a s t _ i d " : 6 4 , " c h a r a c t e r " : " t r o u p e " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 3 , " n a m e " : " t a m i c a w a s h i n g t o n - m i l l e r " , " o r d e r " : 4 3 } , { " c a s t _ i d " : 6 5 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d b " , " g e n d e r " : 1 , " i d " : 1 1 4 5 0 9 8 , " n a m e " : " l u c y b r i a n t " , " o r d e r " : 4 4 } , { " c a s t _ i d " : 6 6 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a d f " , " g e n d e r " : 2 , " i d " : 3 3 3 0 5 , " n a m e " : " n a t h a n m e i s t e r " , " o r d e r " : 4 5 } , { " c a s t _ i d " : 6 7 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 4 , " n a m e " : " g e r r y b l a i r " , " o r d e r " : 4 6 } , { " c a s t _ i d " : 6 8 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e 7 " , " g e n d e r " : 2 , " i d " : 3 3 3 1 1 , " n a m e " : " m a t t h e w c h a m b e r l a i n " , " o r d e r " : 4 7 } , { " c a s t _ i d " : 6 9 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 5 , " n a m e " : " p a u l y a t e s " , " o r d e r " : 4 8 } , { " c a s t _ i d " : 7 0 , " c h a r a c t e r " : " o p c e n t e r d u t y o f f i c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a e f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 6 , " n a m e " : " w r a y w i l s o n " , " o r d e r " : 4 9 } , { " c a s t _ i d " : 7 1 , " c h a r a c t e r " : " o p c e n t e r s t a f f " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 3 " , " g e n d e r " : 2 , " i d " : 5 4 4 9 2 , " n a m e " : " j a m e s g a y l y n " , " o r d e r " : 5 0 } , { " c a s t _ i d " : 7 2 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 7 , " n a m e " : " m e l v i n l e n o c l a r k i i i " , " o r d e r " : 5 1 } , { " c a s t _ i d " : 7 3 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 8 , " n a m e " : " c a r v o n f u t r e l l " , " o r d e r " : 5 2 } , { " c a s t _ i d " : 7 4 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c a f f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 6 9 , " n a m e " : " b r a n d o n j e l k e s " , " o r d e r " : 5 3 } , { " c a s t _ i d " : 7 5 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 0 , " n a m e " : " m i c a h m o c h " , " o r d e r " : 5 4 } , { " c a s t _ i d " : 7 6 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 1 , " n a m e " : " h a n n i y a h m u h a m m a d " , " o r d e r " : 5 5 } , { " c a s t _ i d " : 7 7 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 2 , " n a m e " : " c h r i s t o p h e r n o l e n " , " o r d e r " : 5 6 } , { " c a s t _ i d " : 7 8 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 0 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 3 , " n a m e " : " c h r i s t a o l i v e r " , " o r d e r " : 5 7 } , { " c a s t _ i d " : 7 9 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 4 , " n a m e " : " a p r i l m a r i e t h o m a s " , " o r d e r " : 5 8 } , { " c a s t _ i d " : 8 0 , " c h a r a c t e r " : " d a n c e r " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 7 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 5 , " n a m e " : " b r a v i t a a . t h r e a t t " , " o r d e r " : 5 9 } , { " c a s t _ i d " : 8 1 , " c h a r a c t e r " : " m i n i n g c h i e f ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 6 , " n a m e " : " c o l i n b l e a s d a l e " , " o r d e r " : 6 0 } , { " c a s t _ i d " : 8 2 , " c h a r a c t e r " : " v e t e r a n m i n e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 1 f " , " g e n d e r " : 0 , " i d " : 1 0 7 9 6 9 , " n a m e " : " m i k e b o d n a r " , " o r d e r " : 6 1 } , { " c a s t _ i d " : 8 3 , " c h a r a c t e r " : " r i c h a r d ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 3 " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 7 8 , " n a m e " : " m a t t c l a y t o n " , " o r d e r " : 6 2 } , { " c a s t _ i d " : 8 4 , " c h a r a c t e r " : " n a v \' i ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 7 " , " g e n d e r " : 1 , " i d " : 1 4 7 8 9 8 , " n a m e " : " n i c o l e d i o n n e " , " o r d e r " : 6 3 } , { " c a s t _ i d " : 8 5 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 b " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 0 , " n a m e " : " j a m i e h a r r i s o n " , " o r d e r " : 6 4 } , { " c a s t _ i d " : 8 6 , " c h a r a c t e r " : " t r o o p e r ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 2 f " , " g e n d e r " : 0 , " i d " : 1 2 0 7 2 8 1 , " n a m e " : " a l l a n h e n r y " , " o r d e r " : 6 5 } , { " c a s t _ i d " : 8 7 , " c h a r a c t e r " : " g r o u n d t e c h n i c i a n ( u n c r e d i t e d ) " , " c r e d i t _ i d " : " 5 2 f e 4 8 0 1 9 2 5 1 4 1 6 c 7 5 0 a c b 3 3 " , " g e n d e r " : 2 , " i d " : 1 2 0 7 2 8 2 , " n a m e " : " a n t h o n y i n g r u b e r " , " o r d e r " : 6 6 } , { " c a s t _ i d " : 8 8 , " c h a r a c t e r " : " f l i g h t c r e w m e c h a n i c ( u n c r e d i t e d

In [45]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\khada\AppData\Local\Temp\ipykernel_19332\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [42]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [44]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [45]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [47]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity = cosine_similarity(vectors)

In [50]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2997, np.float64(0.2867696673382022)),
 (61, np.float64(0.27036903521793754)),
 (4405, np.float64(0.26490647141300877)),
 (31, np.float64(0.24525573579398632)),
 (1440, np.float64(0.24525573579398632))]

In [51]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [53]:
recommend('Batman Begins')

Synecdoche, New York
10th & Wolf
Sexy Beast
The Shipping News
Copying Beethoven

In [54]:
new_df.iloc[1216].title

'Autumn in New York'

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have 'tags' column (combined text)
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
vectors = tfidf.fit_transform(new_df['tags']).toarray()

similarity = cosine_similarity(vectors)

def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    
    
    recommended_movies = []
    for i in movies_list:
        recommended_movies.append(new_df.iloc[i[0]].title)
    return recommended_movies

In [56]:
recommend('Batman Begins')

['The Dark Knight',
 'Batman Returns',
 'Batman',
 'Batman',
 'The Dark Knight Rises']

In [57]:
new_df.iloc[1216].title

'Autumn in New York'

In [58]:
import pickle

In [59]:
pickle.dump(new_df, open('movies.pkl','wb'))

In [60]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [61]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl','wb'))

In [62]:
pickle.dump(similarity, open('similarity.pkl','wb'))

In [63]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

NameError: name 'new' is not defined

In [64]:
import pickle
import pandas as pd

movies_dict = pickle.load(open('movie_dict.pkl', 'rb'))
movies = pd.DataFrame(movies_dict)
print(movies.head())
print(movies.columns)

   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                tags
0  in the 22nd century, a parapleg marin is dispa...
1  captain barbossa, long believ to be dead, ha c...
2  a cryptic messag from bond’ past send him on a...
3  follow the death of district attorney harvey d...
4  john carter is a war-weary, former militari ca...
Index(['movie_id', 'title', 'tags'], dtype='object')

In [65]:
import pickle
similarity = pickle.load(open('similarity.pkl', 'rb'))
print(similarity.shape)

(4806, 4806)